### ISSUE TITLE
iPad issue white square in top left cornor

### ISSUE THREAD

**Issue by dklarshansen** [DavdRoman/Bohr#1]
When I run the demo in deploytarget 8.2 / iPad Air there is a white square in the left cornor.

![ios simulator screen shot 23 06 2015 08 53 05](https://cloud.githubusercontent.com/assets/7044654/8300477/92abf0c8-1985-11e5-8cba-e2946074f2c1.png)

**Comment by davdroman** [comment]
I'm about to release v2.0.0 in a few hours fixing that bug and some others :)

I'll let you know when it's ready.

**Comment by davdroman** [comment]
@dklarshansen this is now fixed for v2.0.0 :+1:

**Comment by dklarshansen** [comment]
Thanks :-)
