### ISSUE TITLE
[Feature] DatePickerCell

### ISSUE THREAD

**Issue by minuscorp** [DavdRoman/Bohr#12]
Hi there!

I really love your library, I think there're no resources like this apart from InAppSettingsKit and I really support your job.

I just open the issue to let you know that a **big** feature to this awesome library would be to support DatePicker. I know this is easily extensible and I'll try to implement this feature after this week of holidays as I need it to my settings view.

Keep It up and I'm really looking forward to your next release!

**Comment by davdroman** [comment]
Hi there Jorge! Thank you so much for those nice words.

This feature has already been requested in PR #7, and you can be well sure it's going to be included in version 3, which is coming really really soon :)

**Comment by davdroman** [comment]
Great news! This feature is now part of Bohr 3.0.0 alpha 2! :smile:

**Comment by minuscorp** [comment]
Starting next week, I'll be using this library to the settings section in my new app project. I'll be glad in report new issues if there are and new enhancements and ideas you could add to this awesome library.

Wating **impatiently** for the stable 3 version!

pd. I've read that you dropped Storyboard support, I think it's a plus and it's easier for developers to create some sections and cells programatically :stuck_out_tongue_winking_eye:

**Comment by davdroman** [comment]
Thanks for the kind words, it's coming as fast as possible :)

Also, nicd to hear your opinion about dropping storyboard support.
