### ISSUE TITLE
Alpha.3 Bug.

### ISSUE THREAD

**Issue by antoniocasero** [DavdRoman/Bohr#14]
I think this file is in the project by mistake BOTableViewCell (MacBook Pro de David's conflicted copy 2015-08-26).h

It produces an error when you try to execute the app (Duplicate interface definition) using cocoapods. Should be fixed once is removed.

**Comment by davdroman** [comment]
Sorry for that one! It'll be deleted in next alpha :+1:

**Comment by davdroman** [comment]
Done! :+1:

**Comment by antoniocasero** [comment]
Thanks man!
