### ISSUE TITLE
Dismiss keyboard on background tap or activating other cells

### ISSUE THREAD

**Issue by ealeksandrov** [DavdRoman/Bohr#2]
After presenting a keyboard for textfield the only way to hide it - click `Done` button. If I click other cells or even go through navigation controller keyboard still persists on screen. Personally I want to hide it on interaction with other cells or even with tap on tableview background.

This can be optional configurable behaviour.

**Comment by davdroman** [comment]
Good point. I'll take this into account for future updates.

**Comment by davdroman** [comment]
@ealeksandrov v2.0.0 now supports keyboard dismissal through taps or swipes on the table view :+1:
