### ISSUE TITLE
Swift 2.0 and Xcode 7 Support?

### ISSUE THREAD

**Issue by RayanSaeed** [DavdRoman/Bohr#22]
Is swift supported and if so.. How do I go about using this control in my project? Could you update the "Read Me" or just answer here in this issue?

**Comment by davdroman** [comment]
I haven't really done any Swift related stuff yet so I'm quite unsure about compatibility. I'd really appreciate some help over here from any minimally experienced user.

**Comment by RayanSaeed** [comment]
Oh well. Right now I need to work on another project. But hopefully when I get some free time I'll contribute to this with Swift. I personally think this is a great control. 

Thanks

**Comment by headkit** [comment]
I would  love to see this working in Swift!

**Comment by davdroman** [comment]
Good news!

Now that I've gotten into Swift, I've started adapting all my libraries. A month ago I released a major Swifty version of [**Popsicle**](https://github.com/DavdRoman/Popsicle), and I'm planning on doing the same with Bohr.

I've got plenty of ideas for some cool operators that could greatly simplify Bohr's current blocky setup chaos, and I'd like to hear some suggestions for possible new features suggestions that Swift can enable on Bohr as well.

**Comment by dannyshmueli** [comment]
+1 on the swift support

**Comment by kevinwo** [comment]
In an Objective-C bridging header do:

```
#import <Bohr/Bohr.h>
```

In your subclassed BOTableVIewController:

```
import Bohr
```

Voila!

**Comment by davdroman** [comment]
As @kevinwo expressed, Objective-C bridging does work great and it's a temporary solution until 4.0 comes out.

As this issue is solved, I'll be closing it now. As a side note: anyone interested in taking part in version 4.0 (regardless of their skill or number of contributions) should take a look at #33. Let's make a great Swifty 4.0 together! :smile:
