### ISSUE TITLE
Pod set up

### ISSUE THREAD

**Issue by JeevanThandi** [DavdRoman/Bohr#23]
Hi, The pod installation seems to be missing a significant number of files? Such as BOTableViewSection ?

**Comment by davdroman** [comment]
Hi there @JeevanThandi!

There's nothing wrong with the pod.

The thing is v3.0.0 is marked as a pre-release version as of now, so you need to implicitly ask for such version in order for CocoaPods to install it (given that it only installs the latest stable release), so your Podfile should look like this:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'Bohr', '~> 3.0.0-rc'
```

After `pod install`ing, you should see something like this:

<img width="312" alt="screen shot 2015-09-24 at 14 23 01" src="https://cloud.githubusercontent.com/assets/2538074/10073253/da5aac76-62c7-11e5-8793-d7285896e35e.png">

**Comment by davdroman** [comment]
v3.0.0 is now available, so you should no longer be having trouble with this.

Happy coding! :+1:
