### ISSUE TITLE
Small Animation Issue

### ISSUE THREAD

**Issue by mythodeia** [DavdRoman/Bohr#36]
in the demo project i added the following line between the 2 switches in the 1st section:

```
[section addCell:[BOStepperTableViewCell cellWithTitle:@"Stepper" key:@"stepper" handler:nil]];
```

Now if you try to change value of the 1st switch there is a small animation issue while the tableview is trying to animate switch 2 into the view.

Same goes if i put the stepper as the 1st cell. if however i put the stepper as the 3rd cell (last one of 1st section) the animation works fine

**Comment by davdroman** [comment]
I'm suspicious it could be related to how `BOTableViewController` animates option updates, but I don't know why it's triggered exactly in that specific scenario.

[These lines](https://github.com/DavdRoman/Bohr/blob/master/Bohr/BOTableViewController.m#L180-L211) are definitely worth playing around with to see if the issue persists and how to fix it.

**Comment by gmoledina** [comment]
I experienced this same issue as well. It got solved once I moved the cell that can get displayed/hidden in a separate section. 
I wasn't using a BOStepperTableViewCell so I think it's related to the order/section of cells that use the visibly feature.

**Comment by davdroman** [comment]
> so I think it's related to the order/section of cells that use the visibly feature.

That makes even more sense. We'll need to check the visibility logic for the table view then.

Thanks for shedding some light on the subject, @gmoledina!
