### ISSUE TITLE
Feature request: set static footer programmatically

### ISSUE THREAD

**Issue by ealeksandrov** [DavdRoman/Bohr#4]
Common thing on settings screens - to show version and build number in footer. This can't be done from storyboard, only in runtime, so I want property like `defaultFooterTitle`. It even can be configured for each section. So priorities for section footers will be: 1) storyboard 2) default from property 3) cells dynamic footers.

Thanks!

**Comment by ealeksandrov** [comment]
I propose action for `setup` method - `[self setDefaultFooter:@"Build N here" forSection:0];`

**Comment by davdroman** [comment]
Well thought. I'm totally into the `defaultFooterTitle` thing, but I'd do it for every cell and pick the one from the last cell in every section (keeping mentioned priorities, of course).

It wouldn't take more than 20 lines of code, so let me work on it.

**Comment by ealeksandrov** [comment]
:+1:

**Comment by davdroman** [comment]
There you go!

**Comment by ealeksandrov** [comment]
Thanks a lot!
