### ISSUE TITLE
[self bo_setFont:font] → -[__NSCFNumber length]: unrecognized selector

### ISSUE THREAD

**Issue by kevnm67** [DavdRoman/Bohr#42]
Thanks for providing Bohr. It's been very helpful!

I'm having one issue.  Here are the steps producing the crash:
1. During app launch, I enumerate a tabbar's view controller array -- 1 VC is a subclass of BohrTableViewController
2. Attempt to present a UIPickerView from a completely separate, non-bohr-subclass tableview and the app crashes

```
#import "UILabel+DatePickerCustomization.h"

// line 85
- (void)bo_setFont:(UIFont *)font {
.... [self bo_setFont:font] ;
}
```

**Comment by kevnm67** [comment]
Closed: Sorry, it was an error on my part -- picker data source had NSNumber objects in the array. Xcode kept directing me to your UILabel category.

**Comment by davdroman** [comment]
No problem, I'm glad it's not a bug :+1:
