### ISSUE TITLE
change cell text - question

### ISSUE THREAD

**Issue by mythodeia** [DavdRoman/Bohr#43]
So i have a BOButtonTableViewCell with `Turn Passcode On` when the user first open settings.
When the user taps the button a lock view appears where he can enable a passcode for the app.
When the lockview is dismissed and the user has set his desired passcode i want the text of the button to change to `Turn Passcode Off`

is there any other way to achieve this besides keeping a reference of the cell and changing the title?
i mean just reloading a simple cell
thanks

**Comment by davdroman** [comment]
I don't think Bohr provides with an efficient enough mechanism to do that at the moment, so keeping a reference to the cell (or binding that piece of state to its textLabel through ReactiveCocoa) is the way to go.

**Comment by mythodeia** [comment]
thats was my solution for this. thanks

**Comment by davdroman** [comment]
I'm sorry for not providing a more extensive answer by the way. I've been particularly busy this week.

**Comment by mythodeia** [comment]
@DavdRoman It was a yes or no question and you answered just fine. I know everyone is super busy so no worries. :+1: 
PS: in your next Swift version of this library you can gather up all 'missing' features like this and add it there. thanks again

**Comment by davdroman** [comment]
Absolutely. I'll add it to #33 right away.

**Comment by mythodeia** [comment]
excellent. looking forward to the new version :+1:
